### ISSUE TITLE
with Conneciton.open does not work

### ISSUE THREAD

**Issue by trash-panda-v91-beta** [marian-code/ssh-utilities#1]
Hello,

I'm trying to use following piece of code:
```python
with Connection.open(SSH_USERNAME, HOSTNAME, SSH_KEY) as ssh:
```

but this is not working. VSC is saying following:
Object of type "SSHConnection" cannot be used with "with" because it does not implement __enter__

and then there is this traceback:
```python
    with Connection.open(SSH_USERNAME, HOSTNAME, SSH_KEY) as ssh:
AttributeError: __enter__
```

Can you please check it? Thanks!

BTW thank you for this ssh wrapper, I was looking really long for something similiar.

**Comment by marian-code** [comment]
Hey, thanks for raising this. Now I see there is a mistake in README and docs. `Connection.open` cannot be used as a context manager. You have to use the `Connection` class itself like this:

```python
with Connection(HOSTNAME, local=False) as ssh:
   ssh...
```
`SSH_USERNAME` and `SSH_KEY` corresponding to `HOSTNAME` will be read from your `~/.ssh/config` file.

If you want more customization to explicitly specify `SSH_USERNAME, HOSTNAME, SSH_KEY` you have to use the open method.
