### ISSUE TITLE
Make output after succesfull connection optional

### ISSUE THREAD

**Issue by trash-panda-v91-beta** [marian-code/ssh-utilities#2]
Hi, 

when I succesfully initiate SSH connection, I got this two lines in STDOUT:
```shell
Will login with private RSA key located in /path/to/the/keys
Connecting to server: user@server
```

It would be nice, if we can either supress this output, move it to a logger or make it optional.

If somebody is strugling with this as well, I'm using this workaround now:
```python
import io
trap = io.StringIO()
with redirect_stdout(trap):
    conn = Connection.open(SSH_USERNAME, HOSTNAME, SSH_KEY)
```

**Comment by marian-code** [comment]
For my own use cases this was never needed so I didn't think about it. But now that you mention it it seems perfectly reasonable. I will think about how to best implement this.

**Comment by marian-code** [comment]
I have added new optional argument `quiet` to all initializing methods  which completely mutes the login output. Check out the new version on pypi.
