### ISSUE TITLE
Feature request: allow the use of ssh-agent instead of key file or password

### ISSUE THREAD

**Issue by lainwir3d** [marian-code/ssh-utilities#3]
The backend already support this, it would allow connection through already configured ssh-agent.

**Comment by marian-code** [comment]
- [x] merge changes from @lainwir3d - #4 
- [x] implement ssh agent use in convenience methods

**Comment by marian-code** [comment]
Implemented by 8190a28bf1ec201be89cbbedc40500864048dad8 . So I am closing this
